/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hs.http.server;

import java.io.*;
import java.net.*;
import java.nio.*;
import java.nio.charset.*;

public class App {
    public static void main(String[] args) throws IOException {
        App app = new App();
        app.run();
    }

    private void run() throws IOException {
        //1. Listen
        //이것만 하면 listen 시작함
        ServerSocket listener = new ServerSocket(8080, 0); //backlog->요청 여러개 왔을 때 얼마나 대기 세움
        System.out.println("Listen!");

        //2. Accept
        while (true) {
            Socket socket = listener.accept();
            System.out.println("Accept!");

            //3. Request처리 -> 처리 -> Response(서버 입장에서는 받는 것임)
            Reader reader = new InputStreamReader(socket.getInputStream());
            CharBuffer charBuffer = CharBuffer.allocate(1_000_000);
            reader.read(charBuffer);

            charBuffer.flip();
            System.out.println(charBuffer.toString());

            // 3-1. response
            String body = "Hello world";
            byte[] bytes = body.getBytes(StandardCharsets.UTF_8);
            String message = "" +
                    "HTTP/1.1 200 OK\n" +
                    "Content-Type: text/html; chatset=UTF-8\n" +
                    "Content-Length:" + bytes.length + "\n" +
                    "\n" +
                    body;

            Writer writer = new OutputStreamWriter(socket.getOutputStream());
            writer.write(message);
            writer.flush();

            //4. Close
            socket.close();
        }
//        listener.close();
    }
}
