/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.demo;

import java.sql.*;
import java.util.*;

public class App {
    public static void main(String[] args) throws SQLException {
        String url = "jdbc:postgresql://localhost:5432/postgres";

        Properties properties = new Properties();
        properties.put("user", "postgres");
        properties.put("password", "yoonjulie1*");

        Connection connection = DriverManager.getConnection(url, properties);

        Statement statement = connection.createStatement();

        String query = "SELECT * FROM people";

        ResultSet resultSet = statement.executeQuery(query);
        while (resultSet.next()) {
            String name = resultSet.getString("name");

            System.out.println(name);
        }

//        System.out.println(connection);
    }
}
